version: '3'

services:
  rocketchat:
    image: rocketchat/rocket.chat:5.4.2
    restart: unless-stopped
    volumes:
      - ./uploads:/app/uploads
    environment:
      - PORT=3000
      - ROOT_URL=http://localhost:3000
      - MONGO_URL=mongodb://mongo:27017/rocketchat?replicaSet=rs0
      - MONGO_OPLOG_URL=mongodb://mongo:27017/local?replicaSet=rs0
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DB=rocketchat
      - MONGO_REPLICAS=mongo:27017
      - MONGO_REPLICA_SET=rs0
      - OVERWRITE_SETTING_Show_Setup_Wizard=completed
    ports:
      - "3000:3000"
    depends_on:
      - mongo-init-replica
    networks:
      - evodev-network

  mongo:
    image: mongo:5.0
    restart: unless-stopped
    command: mongod --oplogSize 128 --replSet rs0 --bind_ip_all
    volumes:
      - ./data/db:/data/db
    networks:
      - evodev-network
    hostname: mongo

  mongo-init-replica:
    image: mongo:5.0
    restart: "no"
    depends_on:
      - mongo
    command: >
      bash -c "
        echo 'Waiting for MongoDB to start...'
        sleep 10
        until mongosh --host mongo:27017 --eval 'db.runCommand({ ping: 1 })' > /dev/null 2>&1; do
          echo 'Waiting for MongoDB to be ready...'
          sleep 2
        done
        echo 'MongoDB is ready, initializing replica set...'
        mongosh --host mongo:27017 --eval \"
          rs.initiate({
            _id: 'rs0',
            members: [{_id: 0, host: 'mongo:27017'}]
          })
        \" || echo 'Replica set already initialized'
      "
    networks:
      - evodev-network

  ollama:
    image: ollama/ollama:latest
    restart: unless-stopped
    volumes:
      - ./ollama:/root/.ollama
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_HOST=0.0.0.0
    networks:
      - evodev-network

  evodev-core:
    image: python:3.11-slim
    restart: unless-stopped
    volumes:
      - .:/app
    working_dir: /app
    command: >
      bash -c "pip install -e . && python -m evodev.main"
    depends_on:
      - rocketchat
      - ollama
    environment:
      - ROCKETCHAT_URL=http://rocketchat:3000
      - OLLAMA_URL=http://ollama:11434
    networks:
      - evodev-network

networks:
  evodev-network:
    driver: bridge