[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "autodev"
version = "0.1.6"
description = "Automated Development Environment"
authors = [{ name = "Twoje Imię" }]
requires-python = ">=3.8"
