[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "evodev"
version = "0.1.11"
description = "Automated Development Environment"
authors = [{ name = "Twoje Imię" }]
requires-python = ">=3.8"
