version: '3'

services:
  mongodb:
    image: mongo:5.0
    restart: always
    volumes:
      - ./data_complete/db:/data/db
    command: mongod --oplogSize 128 --replSet rs0
    networks:
      - rocketchat

  mongodb-init:
    image: mongo:5.0
    restart: on-failure
    command: >
      bash -c "sleep 10 && mongosh mongodb/rocketchat --eval \"rs.initiate({ _id: 'rs0', members: [ { _id: 0, host: 'mongodb:27017' } ]})\""
    depends_on:
      - mongodb
    networks:
      - rocketchat

  rocketchat:
    image: registry.rocket.chat/rocketchat/rocket.chat:7.5.1
    restart: always
    volumes:
      - ./uploads_complete:/app/uploads
    environment:
      - ROOT_URL=http://localhost:3100
      - PORT=3000
      - MONGO_URL=mongodb://mongodb:27017/rocketchat
      - MONGO_OPLOG_URL=mongodb://mongodb:27017/local
      - OVERWRITE_SETTING_Show_Setup_Wizard=completed
      - MAIL_URL=smtp://dummy:dummy@localhost:25
      - OVERWRITE_SETTING_Email_Verification=false
      - OVERWRITE_SETTING_Accounts_EmailVerification=false
      - OVERWRITE_SETTING_Accounts_ManuallyApproveNewUsers=false
      - OVERWRITE_SETTING_Accounts_AllowEmailChange=true
      - OVERWRITE_SETTING_Accounts_AllowPasswordChange=true
      - OVERWRITE_SETTING_Accounts_RequirePasswordConfirmation=false
    depends_on:
      - mongodb
    ports:
      - 3100:3000
    networks:
      - rocketchat
      - system_network

networks:
  rocketchat:
    driver: bridge
  system_network:
    external: true
