version: '3.8'

services:
  mongodb:
    image: mongo:5.0
    restart: always
    volumes:
      - ${DATA_DIR:-../../../data}/mongodb:/data/db
    command: mongod --oplogSize 128 --replSet rs0
    networks:
      - rocketchat
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  mongodb-init:
    image: mongo:5.0
    restart: on-failure
    command: >
      bash -c "sleep 10 && mongosh mongodb/rocketchat --eval \"rs.initiate({ _id: 'rs0', members: [ { _id: 0, host: 'mongodb:27017' } ]})\""
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - rocketchat

  rocketchat:
    build: .
    restart: always
    volumes:
      - ${DATA_DIR:-../../../data}/uploads:/app/uploads
    environment:
      - ROOT_URL=http://localhost:${ROCKETCHAT_PORT:-3100}
      - MONGO_URL=mongodb://mongodb:27017/rocketchat
      - MONGO_OPLOG_URL=mongodb://mongodb:27017/local
      - PORT=3000
      # Skip setup wizard
      - OVERWRITE_SETTING_Show_Setup_Wizard=completed
      # Admin user configuration
      - ADMIN_USERNAME=${ROCKETCHAT_ADMIN_USERNAME:-admin}
      - ADMIN_PASS=${ROCKETCHAT_ADMIN_PASSWORD:-dxIsDLnhiqKfDt5J}
      - ADMIN_EMAIL=${ROCKETCHAT_ADMIN_EMAIL:-admin@example.com}
      # Disable registration and require admin for new users
      - OVERWRITE_SETTING_Accounts_RegistrationForm=disabled
      - OVERWRITE_SETTING_Accounts_ManuallyApproveNewUsers=true
    depends_on:
      mongodb-init:
        condition: service_completed_successfully
    ports:
      - ${ROCKETCHAT_PORT:-3100}:3000
    networks:
      - rocketchat
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/info"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  rocketchat:
    driver: bridge
    name: rocketchat_network
